Repository uc-cdis/gen3-code-vigil, pull requests merged in 2024-09, with the labels that each got.

#107 Migrate OIDC client Tests
  .github/workflows/shared_integration_tests.yaml
  .secrets.baseline
  gen3-integration-tests/conftest.py
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-audit-service-logging.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-check-kube-job-pod.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-check_indices_after_etl.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-clean-up-indices.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-create-access-token.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-create-link-google-test-buckets.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-fence-client-rotate.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-fence-create-client.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-fence-delete-client.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-fence-disable-register-users-redirect.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-fence-enable-register-users-redirect.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-fence-force-link-google.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-fetch-configs.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-generate-api-key.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-kube-setup-service.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-modify-env-for-service-pr.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-modify-env-for-test-repo-pr.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-revoke-arborist-policy.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-run-gen3-command.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-run-gen3-job.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-save-pod-logs.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-select-and-lock-namespace.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-unlock-namespace.groovy
  gen3-integration-tests/pages/login.py
  gen3-integration-tests/pyproject.toml
  gen3-integration-tests/services/fence.py
  gen3-integration-tests/tests/test_centralized_auth.py
  gen3-integration-tests/tests/test_client_credentials.py
  gen3-integration-tests/tests/test_oauth2.py
  gen3-integration-tests/tests/test_oidc_client.py
  gen3-integration-tests/utils/gen3_admin_tasks.py
  gen3-integration-tests/utils/test_setup.py
Labels: TestHomePage

#108 Update namespace for kubectl commands
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-audit-service-logging.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-check_indices_after_etl.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-clean-up-indices.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-fence-client-rotate.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-fence-create-client.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-fence-disable-register-users-redirect.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-fence-enable-register-users-redirect.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-fetch-configs.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-modify-env-for-service-pr.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-modify-env-for-test-repo-pr.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-run-gen3-job.groovy
Labels: TestHomePage, jenkins-genomel

#104 Migrate authN tests
  .github/workflows/integration_tests.yaml
  .github/workflows/shared_integration_tests.yaml
  .secrets.baseline
  gen3-integration-tests/conftest.py
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-check-kube-job-pod.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-create-access-token.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-fence-create-client.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-fence-delete-client.groovy
  gen3-integration-tests/pages/login.py
  gen3-integration-tests/services/ras.py
  gen3-integration-tests/tests/test_ras_authn.py
Labels: TestDiscoveryPage, TestCentralizedAuth

#109 Chore/run tests local helm
  .github/workflows/shared_integration_tests.yaml
  docs/howto/run_tests_on_local_helm_instance.md
  gen3-integration-tests/README.md
  gen3-integration-tests/conftest.py
  gen3-integration-tests/pages/login.py
  gen3-integration-tests/pages/study_viewer.py
  gen3-integration-tests/pyproject.toml
  gen3-integration-tests/scripts/helm/extract_db_creds.sh
  gen3-integration-tests/scripts/helm/generate_api_keys.sh
  gen3-integration-tests/test_data/test_setup/clients.csv
  gen3-integration-tests/test_data/test_setup/users.csv
  gen3-integration-tests/tests/test_aggregate_mds.py
  gen3-integration-tests/tests/test_discoverypage.py
  gen3-integration-tests/tests/test_etl.py
  gen3-integration-tests/tests/test_study_registration.py
  gen3-integration-tests/utils/gen3_admin_tasks.py
  gen3-integration-tests/utils/jenkins.py
  gen3-integration-tests/utils/test_setup.py
Labels: TestHomePage

#111 Fix Username Lookup when useProfileDropdown is enabled
  gen3-integration-tests/pages/login.py
Labels: jenkins-brain, TestHomePage

#110 Refactor - Setup Fence Test Clients
  gen3-integration-tests/conftest.py
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-create-link-google-test-buckets.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-fence-client-rotate.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-setup-fence-test-clients.groovy
  gen3-integration-tests/utils/gen3_admin_tasks.py
  gen3-integration-tests/utils/test_setup.py
Labels: TestAggregateMDS, TestDataUpload, TestGoogleDataAccess

#114 Collect test suites list
  gen3-integration-tests/conftest.py
  gen3-integration-tests/gen3_ci/scripts/save_ci_env_pod_logs.py
  gen3-integration-tests/list_test_suites.py
Labels: TestHomePage

#113 Remove google linking tests as the functionality is deprecated
  gen3-integration-tests/poetry.lock
  gen3-integration-tests/services/fence.py
  gen3-integration-tests/tests/test_link_google_account.py
Labels: TestMetadataIngestion
