Repository uc-cdis/gen3-code-vigil, pull requests merged in 2024-10, with the labels that each got.

#112 Chore/test modifications for helm
  .secrets.baseline
  gen3-integration-tests/services/guppy.py
  gen3-integration-tests/test_data/guppy/test_query1.json
  gen3-integration-tests/test_data/guppy/test_query2.json
  gen3-integration-tests/test_data/guppy/test_query3.json
  gen3-integration-tests/test_data/guppy/test_query4.json
  gen3-integration-tests/test_data/guppy/test_query5.json
  gen3-integration-tests/test_data/guppy/test_query6.json
  gen3-integration-tests/test_data/guppy/test_query7.json
  gen3-integration-tests/test_data/guppy/test_query8.json
  gen3-integration-tests/test_data/guppy/test_response1.json
  gen3-integration-tests/test_data/guppy/test_response2.json
  gen3-integration-tests/test_data/guppy/test_response3.json
  gen3-integration-tests/test_data/guppy/test_response4.json
  gen3-integration-tests/test_data/guppy/test_response5.json
  gen3-integration-tests/test_data/guppy/test_response6.json
  gen3-integration-tests/test_data/guppy/test_response7.json
  gen3-integration-tests/test_data/guppy/test_response8.json
  gen3-integration-tests/test_data/test_setup/clients.csv
  gen3-integration-tests/test_data/test_setup/guppy_es_indexes/es_indexes_data/array_mapping.json
  gen3-integration-tests/test_data/test_setup/guppy_es_indexes/es_indexes_data/configs_alias.json
  gen3-integration-tests/test_data/test_setup/guppy_es_indexes/es_indexes_data/file_alias.json
  gen3-integration-tests/test_data/test_setup/guppy_es_indexes/es_indexes_data/file_batch.ndjson
  gen3-integration-tests/test_data/test_setup/guppy_es_indexes/es_indexes_data/file_mapping.json
  gen3-integration-tests/test_data/test_setup/guppy_es_indexes/es_indexes_data/subject_alias.json
  gen3-integration-tests/test_data/test_setup/guppy_es_indexes/es_indexes_data/subject_batch.ndjson
  gen3-integration-tests/test_data/test_setup/guppy_es_indexes/es_indexes_data/subject_mapping.json
  gen3-integration-tests/test_data/test_setup/guppy_es_indexes/es_indexes_data/toy_batch.ndjson
  gen3-integration-tests/test_data/test_setup/guppy_es_indexes/es_indexes_data/toy_mapping.json
  gen3-integration-tests/test_data/test_setup/guppy_es_indexes/helm_setup.sh
  gen3-integration-tests/test_data/test_setup/guppy_es_indexes/jenkins_setup.sh
  gen3-integration-tests/tests/test_audit_service.py
  gen3-integration-tests/tests/test_client_credentials.py
  gen3-integration-tests/tests/test_dbgap.py
  gen3-integration-tests/tests/test_etl.py
  gen3-integration-tests/tests/test_graph_submit_and_query.py
  gen3-integration-tests/tests/test_guppy_service.py
  gen3-integration-tests/tests/test_indexing_page.py
  gen3-integration-tests/tests/test_oidc_client.py
  gen3-integration-tests/tests/test_register_user.py
  gen3-integration-tests/tests/test_study_registration.py
  gen3-integration-tests/tests/test_user_token.py
  gen3-integration-tests/utils/gen3_admin_tasks.py
  gen3-integration-tests/utils/test_setup.py
Labels: TestAuditService, TestHomePage

#115 Helm - OIDC delete-expired-clients
  .secrets.baseline
  gen3-integration-tests/tests/test_oidc_client.py
  gen3-integration-tests/utils/gen3_admin_tasks.py
Labels: TestHomePage

#116 Helm Change for Revoke Arborist Policy
  gen3-integration-tests/services/fence.py
  gen3-integration-tests/utils/gen3_admin_tasks.py
Labels: TestDataUpload

#119 Helm ETL Suite Changes
  gen3-integration-tests/test_data/test_setup/guppy_es_indexes/es_indexes_data/configs_alias.json
  gen3-integration-tests/test_data/test_setup/guppy_es_indexes/es_indexes_data/file_alias.json
  gen3-integration-tests/test_data/test_setup/guppy_es_indexes/es_indexes_data/subject_alias.json
  gen3-integration-tests/utils/gen3_admin_tasks.py
Labels: TestAggregateMDS, TestGen3Client

#121 Fix Logged in User Case Issue
  gen3-integration-tests/pages/login.py
  gen3-integration-tests/services/audit.py
Labels: jenkins-brain, TestAuditService, TestHomePage

#125 Chore/more docs updates
  gen3-integration-tests/README.md
  gen3-integration-tests/test_data/test_setup/user.yaml
Labels: TestHomePage
