Repository uc-cdis/gen3-code-vigil, pull requests merged in 2024-08, with the labels that each got.

#77 Chore/add indexd service
  .gitignore
  .secrets.baseline
  gen3-integration-tests/conftest.py
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-create-link-google-test-buckets.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/fence-create-client.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/fence-delete-client.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/generate-api-keys.groovy
  gen3-integration-tests/gen3_ci/scripts/generate_slack_report.py
  gen3-integration-tests/gen3_ci/scripts/prepare_ci_environment.py
  gen3-integration-tests/pages/submission.py
  gen3-integration-tests/pyproject.toml
  gen3-integration-tests/services/audit.py
  gen3-integration-tests/services/fence.py
  gen3-integration-tests/services/graph.py
  gen3-integration-tests/services/guppy.py
  gen3-integration-tests/services/indexd.py
  gen3-integration-tests/services/ras.py
  gen3-integration-tests/tests/test_audit_service.py
  gen3-integration-tests/tests/test_centralized_auth.py
  gen3-integration-tests/tests/test_client_credentials.py
  gen3-integration-tests/tests/test_data_upload.py
  gen3-integration-tests/tests/test_dbgap.py
  gen3-integration-tests/tests/test_discoverypage.py
  gen3-integration-tests/tests/test_gen3client.py
  gen3-integration-tests/tests/test_graph_submit_and_query.py
  gen3-integration-tests/tests/test_oauth2.py
  gen3-integration-tests/tests/test_presigned_url.py
  gen3-integration-tests/tests/test_ras_drs.py
  gen3-integration-tests/utils/gen3_admin_tasks.py
  gen3-integration-tests/utils/test_setup.py
Labels: TestHomePage

#98 Migration Fix - Indexd Ras DRS
  .secrets.baseline
  gen3-integration-tests/pages/login.py
  gen3-integration-tests/pages/workspace.py
  gen3-integration-tests/tests/test_aggregate_mds.py
  gen3-integration-tests/tests/test_ras_drs.py
  gen3-integration-tests/utils/test_execution.py
Labels: TestAuditService

#101 Wait for usersync job to complete after fence client creation
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-generate-api-key.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/fence-create-client.groovy
  gen3-integration-tests/gen3_ci/scripts/prepare_ci_environment.py
Labels: TestAuditService, TestGen3Client

#93 Migration - Fence DrsEndpoint Tests
  .secrets.baseline
  gen3-integration-tests/services/drs.py
  gen3-integration-tests/services/fence.py
  gen3-integration-tests/tests/test_drs_endpoint.py
Labels: TestAggregateMDS, TestDiscoveryPage, TestDataUpload

#99 Migrate Link Google Account Tests
  gen3-integration-tests/gen3_ci/jenkins_jobs/fence-force-link-google.groovy
  gen3-integration-tests/services/fence.py
  gen3-integration-tests/tests/test_link_google_account.py
  gen3-integration-tests/utils/gen3_admin_tasks.py
Labels: TestGraphSubmitAndQuery, TestLinkGoogleAccount

#100 Skip RAS DRS test cases and remove object from indexd record
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-modify-env-for-service-pr.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-modify-env-for-test-repo-pr.groovy
  gen3-integration-tests/pages/login.py
  gen3-integration-tests/pages/workspace.py
  gen3-integration-tests/tests/test_client_credentials.py
  gen3-integration-tests/tests/test_dbgap.py
  gen3-integration-tests/tests/test_discoverypage.py
  gen3-integration-tests/tests/test_ras_drs.py
  gen3-integration-tests/tests/test_study_viewer.py
Labels: TestDiscoveryPage

#91 Migration - Fence UserToken Tests
  gen3-integration-tests/conftest.py
  gen3-integration-tests/pages/login.py
  gen3-integration-tests/pyproject.toml
  gen3-integration-tests/services/drs.py
  gen3-integration-tests/services/fence.py
  gen3-integration-tests/tests/test_drs_endpoint.py
  gen3-integration-tests/tests/test_user_token.py
  gen3-integration-tests/utils/test_setup.py
Labels: TestAuditService, TestAggregateMDS

#97 Migration - Fence Portal RAS Register Users
  .pre-commit-config.yaml
  .secrets.baseline
  gen3-integration-tests/conftest.py
  gen3-integration-tests/gen3_ci/jenkins_jobs/fence-create-client.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/fence-delete-client.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/fence-disable-register-users-redirect.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/fence-enable-register-users-redirect.groovy
  gen3-integration-tests/pages/login.py
  gen3-integration-tests/pages/user_register.py
  gen3-integration-tests/poetry.lock
  gen3-integration-tests/pyproject.toml
  gen3-integration-tests/tests/test_audit_service.py
  gen3-integration-tests/tests/test_centralized_auth.py
  gen3-integration-tests/tests/test_login_page.py
  gen3-integration-tests/tests/test_ras_authn.py
  gen3-integration-tests/tests/test_register_user.py
  gen3-integration-tests/utils/gen3_admin_tasks.py
Labels: jenkins-blood, TestHomePage

#105 General fixes
  .github/workflows/shared_integration_tests.yaml
  .secrets.baseline
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-audit-service-logging.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-check-kube-job-pod.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-check_indices_after_etl.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-clean-up-indices.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-create-access-token.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-fence-create-client.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-fence-delete-client.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-fence-disable-register-users-redirect.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-fence-enable-register-users-redirect.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-fence-force-link-google.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-kube-setup-service.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-mutate-manifest-for-guppy-test.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-revoke-arborist-policy.groovy
  gen3-integration-tests/tests/test_audit_service.py
  gen3-integration-tests/tests/test_data_upload.py
  gen3-integration-tests/tests/test_dataguids.py
  gen3-integration-tests/tests/test_discoverypage.py
  gen3-integration-tests/tests/test_graph_submit_and_query.py
  gen3-integration-tests/tests/test_pfb_export.py
  gen3-integration-tests/tests/test_ras_authn.py
  gen3-integration-tests/tests/test_requestor.py
  gen3-integration-tests/tests/test_study_registration.py
  gen3-integration-tests/utils/gen3_admin_tasks.py
Labels: TestHomePage
