Repository uc-cdis/gen3-code-vigil, pull requests merged in 2024-11, with the labels that each got.

#127 Mitigating OOM errors in the job
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-generate-api-keys.groovy
Labels: TestHomePage

#128 Fix logic to skip tests for doc changes
  .github/workflows/shared_integration_tests.yaml
  gen3-integration-tests/README.md
Labels: TestHomePage

#129 Fence - Cascading Auth Test Case
  .secrets.baseline
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-create-link-google-test-buckets.groovy
  gen3-integration-tests/poetry.lock
  gen3-integration-tests/pyproject.toml
  gen3-integration-tests/tests/test_dbgap.py
Labels: TestAuditService, TestDataUpload

#131 Error handling for API key generation
  gen3-integration-tests/gen3_ci/scripts/prepare_ci_environment.py
Labels: TestAuditService, TestAggregateMDS, TestDataUpload

#130 Update docs for running tests against helm on EC2
  gen3-integration-tests/docs/howto/group_tests_from_multiple_suites.md
  gen3-integration-tests/docs/howto/run_tests/on_helm_on_ec2.md
Labels: TestHomePage

#132 Replay PRs from qa-bot command
  gen3-integration-tests/gen3_ci/scripts/generate_slack_report.py
Labels: TestHomePage

#133 Wait for non-null build result after jenkins job completion
  gen3-integration-tests/utils/jenkins.py
Labels: TestHomePage

#135 Retry fetching namespaces and wait longer to select CI env
  gen3-integration-tests/gen3_ci/scripts/select_ci_environment.py
Labels: TestHomePage

#134 Add new markers for sanity and data_upload
  .secrets.baseline
  gen3-integration-tests/pyproject.toml
  gen3-integration-tests/tests/test_data_upload.py
  gen3-integration-tests/tests/test_discoverypage.py
  gen3-integration-tests/tests/test_etl.py
  gen3-integration-tests/tests/test_gen3client.py
  gen3-integration-tests/tests/test_gen3ff_landing_page.py
  gen3-integration-tests/tests/test_guppy_service.py
  gen3-integration-tests/tests/test_homepage.py
  gen3-integration-tests/tests/test_indexing_page.py
  gen3-integration-tests/tests/test_manifest_service.py
  gen3-integration-tests/tests/test_metadata_ingestion.py
  gen3-integration-tests/tests/test_requestor.py
  gen3-integration-tests/tests/test_workspace.py
Labels: TestHomePage

#136 Add support for multiple QUAY_REPO image check
  gen3-integration-tests/gen3_ci/scripts/prepare_ci_environment.py
Labels: TestAuditService

#140 Update pytest.auth_headers with auth access_token headers
  gen3-integration-tests/conftest.py
  gen3-integration-tests/services/fence.py
  gen3-integration-tests/services/indexd.py
  gen3-integration-tests/services/requestor.py
  gen3-integration-tests/utils/test_setup.py
Labels: TestCentralizedAuth, TestRequestor

#120 Test Migration - Argro-wrapper
  gen3-integration-tests/pages/gwas.py
  gen3-integration-tests/pages/login.py
  gen3-integration-tests/pyproject.toml
  gen3-integration-tests/tests/test_argo_wrapper.py
Labels: not-ready-for-ci

#139 Changes for QUAY_REPO support for multiple repos
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-modify-env-for-service-pr.groovy
  gen3-integration-tests/gen3_ci/scripts/prepare_ci_environment.py
Labels: TestAggregateMDS, TestWorkspacePage

#141 Update requestor.py
  gen3-integration-tests/services/requestor.py
Labels: TestStudyViewer, TestClientCredentials
