Repository uc-cdis/gen3-code-vigil, pull requests merged in 2024-07, with the labels that each got.

#74 Migration - indexing page tests
  .secrets.baseline
  gen3-integration-tests/gen3_ci/jenkins_jobs/check-kube-job-pod.groovy
  gen3-integration-tests/pages/indexing_page.py
  gen3-integration-tests/pyproject.toml
  gen3-integration-tests/test_data/indexing_page/invalid_test_manifest.tsv
  gen3-integration-tests/test_data/indexing_page/valid_test_manifest.tsv
  gen3-integration-tests/tests/test_indexing_page.py
  gen3-integration-tests/utils/gen3_admin_tasks.py
Labels: TestIndexingPage

#60 Migrate PFBExport tests
  gen3-integration-tests/pages/exploration.py
  gen3-integration-tests/poetry.lock
  gen3-integration-tests/pyproject.toml
  gen3-integration-tests/services/metadataservice.py
  gen3-integration-tests/tests/test_pfb_export.py
  gen3-integration-tests/utils/gen3_admin_tasks.py
Labels: TestAggregateMDS, TestPFBExport

#87 Fix test labels
  gen3-integration-tests/pages/exploration.py
  gen3-integration-tests/pyproject.toml
  gen3-integration-tests/tests/test_pfb_export.py
Labels: TestPFBExport

#80 Migration - Study Viewer tests
  gen3-integration-tests/gen3_ci/jenkins_jobs/generate-api-keys.groovy
  gen3-integration-tests/pages/study_viewer.py
  gen3-integration-tests/services/requestor.py
  gen3-integration-tests/tests/test_study_viewer.py
Labels: TestAggregateMDS, TestRequestor

#92 Migration - dataguids tests
  gen3-integration-tests/conftest.py
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-fetch-configs.groovy
  gen3-integration-tests/services/graph.py
  gen3-integration-tests/tests/test_dataguids.py
Labels: TestGraphSubmitAndQuery, TestHomePage
