Repository uc-cdis/gen3-code-vigil, pull requests merged in 2025-07, with the labels that each got.

#229 Fix/register user midrc
  gen3-integration-tests/pages/exploration.py
  gen3-integration-tests/tests/test_register_user.py
Labels: TestRegisterUser

#237 Add hostname to adminvm envs in helm-based CI pipeline
  gen3-integration-tests/gen3_ci/scripts/select_ci_environment.py
Labels: TestHomePage

#238 Backward compatible hostname setting for adminvm CI
  gen3-integration-tests/gen3_ci/scripts/select_ci_environment.py
Labels: TestHomePage

#239 Fix hostname for adminvm CI
  .github/workflows/integration_tests.yaml
  .github/workflows/shared_integration_tests.yaml
  gen3-integration-tests/gen3_ci/scripts/select_ci_environment.py
Labels: TestHomePage

#248 adding cedar configuration for CI envs
  gen3-integration-tests/gen3_ci/default_manifest/values/values.yaml
Labels: TestHomePage

#249 Handle multiple jobs
  gen3-integration-tests/utils/gen3_admin_tasks.py
  gen3-integration-tests/utils/test_setup.py
Labels: TestAggregateMDS, TestDiscoveryPage, TestETL

#253 Add logic for skip service image update for certain service repos
  gen3-integration-tests/scripts/helm/env_setup.sh
Labels: TestRegisterUser

#252 Fix: Broken guppy_test due to an f-string error
  gen3-integration-tests/utils/gen3_admin_tasks.py
Labels: TestHomePage

#255 Pelican sower job image update
  gen3-integration-tests/scripts/helm/env_setup.sh
Labels: TestHomePage, TestRegisterUser

#257 Update indexs3client image for indexs3client repo CI run
  gen3-integration-tests/scripts/helm/env_setup.sh
Labels: TestGuppyService

#259 Handle data-simulator CI
  .github/workflows/integration_tests.yaml
  .github/workflows/shared_integration_tests.yaml
  gen3-integration-tests/gen3_ci/scripts/prepare_ci_environment.py
Labels: TestHomePage

#258 Add Argo-wrapper and cohort-middleware services to default ci manifest
  gen3-integration-tests/gen3_ci/default_manifest/values/values.yaml
Labels: TestRegisterUser

#267 adding the GCP "cloud run" script to gen3-code-vigil for documentation and reference.
  gen3-integration-tests/gen3_ci/gcp_cleanup/Dockerfile
  gen3-integration-tests/gen3_ci/gcp_cleanup/cleanup_google_resources.md
  gen3-integration-tests/gen3_ci/gcp_cleanup/main.py
  gen3-integration-tests/gen3_ci/gcp_cleanup/requirements.txt
  gen3-integration-tests/gen3_ci/helm_cleanup/helm-ci-cleanup.yaml
Labels: TestHomePage

#272 Skip RegisterUser Test
  gen3-integration-tests/pages/exploration.py
  gen3-integration-tests/tests/test_register_user.py
Labels: TestRegisterUser

#271 Use CI default from gen3-gitops
  .github/workflows/shared_integration_tests.yaml
  gen3-integration-tests/gen3_ci/default_manifest/Chart.yaml
  gen3-integration-tests/gen3_ci/default_manifest/templates/app.yaml
  gen3-integration-tests/gen3_ci/default_manifest/values.yaml
  gen3-integration-tests/gen3_ci/default_manifest/values/etl.yaml
  gen3-integration-tests/gen3_ci/default_manifest/values/fence.yaml
  gen3-integration-tests/gen3_ci/default_manifest/values/guppy.yaml
  gen3-integration-tests/gen3_ci/default_manifest/values/portal.yaml
  gen3-integration-tests/gen3_ci/default_manifest/values/values.yaml
  gen3-integration-tests/gen3_ci/scripts/prepare_ci_environment.py
Labels: TestAggregateMDS, TestRegisterUser

#273 Update SED command to update FRAME_ANCESTOR
  gen3-integration-tests/scripts/helm/env_setup.sh
Labels: TestHomePage
