Repository uc-cdis/gen3-code-vigil, pull requests merged in 2025-03, with the labels that each got.

#159 creating a more verbose "generate_api_keys" script.
  gen3-integration-tests/Dockerfile
  gen3-integration-tests/scripts/helm/generate_api_keys.sh
Labels: TestGraphSubmitAndQuery, TestDbgap, TestRasAuthN

#160 Update manifest.json for gen3 command runs
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-audit-service-logging.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-check_indices_after_etl.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-clean-up-indices.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-create-access-token.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-create-link-google-test-buckets.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-fence-delete-client.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-fence-disable-register-users-redirect.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-fence-enable-register-users-redirect.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-fence-force-link-google.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-generate-api-key.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-generate-api-keys.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-kube-setup-service.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-mutate-manifest-for-guppy-test.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-revoke-arborist-policy.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-run-gen3-command.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-run-gen3-job.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-save-pod-logs.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-setup-fence-test-clients.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/generate-api-keys.groovy
Labels: TestAggregateMDS

#162 Fix test data for DiscoveryPageTest on HEAL PRs
  gen3-integration-tests/test_data/aggregate_mds/study1.json
  gen3-integration-tests/test_data/aggregate_mds/study2.json
Labels: TestDiscoveryPage

#163 Comment Error message on PR and slack
  .github/workflows/shared_integration_tests.yaml
Labels: TestHomePage

#165 Update .pre-commit-config.yaml
  .pre-commit-config.yaml
Labels: TestHomePage

#164 Update groovy scripts to resolve manifest.json tube issue
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-audit-service-logging.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-check_indices_after_etl.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-clean-up-indices.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-create-access-token.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-create-link-google-test-buckets.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-fence-delete-client.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-fence-disable-register-users-redirect.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-fence-enable-register-users-redirect.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-fence-force-link-google.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-generate-api-key.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-generate-api-keys.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-kube-setup-service.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-mutate-manifest-for-guppy-test.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-revoke-arborist-policy.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-run-gen3-command.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-run-gen3-job.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-save-pod-logs.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-setup-fence-test-clients.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/generate-api-keys.groovy
Labels: TestDataUpload
