Repository uc-cdis/gen3-code-vigil, pull requests merged in 2025-05, with the labels that each got.

#194 Update test_data_upload.py to skip if metadata service isnt running
  gen3-integration-tests/tests/test_data_upload.py
Labels: TestHomePage

#195 Add an ssh-keyscan step in CI to preload the sftp-qa.planx-pla.net ho…
  .github/workflows/shared_integration_tests.yaml
Labels: TestHomePage

#201 Ssh-keyscaning the second sftp server, likely culprit for failing dbg…
  .github/workflows/shared_integration_tests.yaml
Labels: TestDiscoveryPage, TestDataUpload

#200 Gen3-user-data-library Tests
  gen3-integration-tests/pyproject.toml
  gen3-integration-tests/services/userdatalibrary.py
  gen3-integration-tests/tests/test_user_data_library.py
Labels: TestDiscoveryPage

#204 Skip RAS tests for Gen3-Helm if not a nightly-build PR
  .secrets.baseline
  gen3-integration-tests/tests/test_audit_service.py
  gen3-integration-tests/tests/test_ras_authn.py
Labels: TestUserDataLibrary

#202 Increase timeouts for workspace, audit service and etl
  .secrets.baseline
  gen3-integration-tests/pages/workspace.py
  gen3-integration-tests/services/audit.py
  gen3-integration-tests/tests/test_audit_service.py
  gen3-integration-tests/utils/gen3_admin_tasks.py
Labels: TestPFBExport

#205 Run Guppy mutation for PFB Export in gitops-qa
  gen3-integration-tests/tests/test_pfb_export.py
Labels: TestPFBExport

#206 Trigger dependabot PRs manually
  .github/workflows/shared_integration_tests.yaml
Labels: TestHomePage

#210 Fix Audit Tests Skip Logic
  gen3-integration-tests/tests/test_audit_service.py
Labels: TestAuditService

#209 Clean up github workflow
  .github/workflows/shared_integration_tests.yaml
Labels: TestHomePage

#208 Clean test code to move objects into setup class
  .secrets.baseline
  gen3-integration-tests/tests/test_centralized_auth.py
  gen3-integration-tests/tests/test_data_upload.py
  gen3-integration-tests/tests/test_dataguids.py
  gen3-integration-tests/tests/test_dbgap.py
  gen3-integration-tests/tests/test_dicom_viewer.py
  gen3-integration-tests/tests/test_discoverypage.py
  gen3-integration-tests/tests/test_drs_endpoint.py
  gen3-integration-tests/tests/test_etl.py
  gen3-integration-tests/tests/test_google_data_access.py
  gen3-integration-tests/tests/test_graph_submit_and_query.py
  gen3-integration-tests/tests/test_login_page.py
  gen3-integration-tests/tests/test_oauth2.py
  gen3-integration-tests/tests/test_pfb_export.py
  gen3-integration-tests/tests/test_presigned_url.py
  gen3-integration-tests/tests/test_ras_authn.py
  gen3-integration-tests/tests/test_ras_drs.py
  gen3-integration-tests/tests/test_register_user.py
  gen3-integration-tests/tests/test_requestor.py
  gen3-integration-tests/tests/test_study_registration.py
  gen3-integration-tests/tests/test_study_viewer.py
  gen3-integration-tests/tests/test_user_token.py
Labels: TestDiscoveryPage
