Repository uc-cdis/gen3-code-vigil, pull requests merged in 2025-01, with the labels that each got.

#149 Fix Audit Services - RAS login issue
  .secrets.baseline
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-generate-api-keys.groovy
  gen3-integration-tests/services/audit.py
  gen3-integration-tests/tests/test_audit_service.py
  gen3-integration-tests/tests/test_ras_authn.py
Labels: TestAuditService, TestDbgap, TestGoogleDataAccess

#150 Change for Google SA Keys deletion
  .secrets.baseline
  gen3-integration-tests/services/fence.py
  gen3-integration-tests/tests/test_dbgap.py
  gen3-integration-tests/tests/test_google_data_access.py
Labels: TestDbgap, TestGoogleDataAccess

#147 Dicom Viewer Tests
  gen3-integration-tests/pages/dicom.py
  gen3-integration-tests/pages/login.py
  gen3-integration-tests/poetry.lock
  gen3-integration-tests/pyproject.toml
  gen3-integration-tests/services/dicom.py
  gen3-integration-tests/test_data/dicom/test_file.dcm
  gen3-integration-tests/test_data/test_setup/dicom_viewer_es/helm_setup.sh
  gen3-integration-tests/test_data/test_setup/dicom_viewer_es/index_data/imaging_study_alias.json
  gen3-integration-tests/test_data/test_setup/dicom_viewer_es/index_data/imaging_study_batch.ndjson
  gen3-integration-tests/test_data/test_setup/dicom_viewer_es/index_data/imaging_study_mapping.json
  gen3-integration-tests/test_data/test_setup/dicom_viewer_es/jenkins_setup.sh
  gen3-integration-tests/tests/test_dicom_viewer.py
Labels: TestDicomViewer

#151 Handle fence client id and secret retrieval issue
  gen3-integration-tests/utils/test_setup.py
Labels: TestAuditService

#146 Chore/custom cloud auto branch
  .github/workflows/shared_integration_tests.yaml
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-audit-service-logging.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-check-kube-job-pod.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-check_indices_after_etl.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-clean-up-indices.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-create-access-token.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-create-link-google-test-buckets.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-fence-delete-client.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-fence-disable-register-users-redirect.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-fence-enable-register-users-redirect.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-fence-force-link-google.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-fetch-configs.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-generate-api-key.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-generate-api-keys.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-kube-setup-service.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-modify-env-for-service-pr.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-modify-env-for-test-repo-pr.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-mutate-manifest-for-guppy-test.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-revoke-arborist-policy.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-run-gen3-command.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-run-gen3-job.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-save-pod-logs.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-select-and-lock-namespace.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-setup-fence-test-clients.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-unlock-namespace.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/generate-api-keys.groovy
  gen3-integration-tests/gen3_ci/scripts/prepare_ci_environment.py
  gen3-integration-tests/gen3_ci/scripts/release_ci_environment.py
  gen3-integration-tests/gen3_ci/scripts/save_ci_env_pod_logs.py
  gen3-integration-tests/gen3_ci/scripts/select_ci_environment.py
  gen3-integration-tests/utils/gen3_admin_tasks.py
Labels: TestHomePage
