Repository uc-cdis/gen3-code-vigil, pull requests merged in 2025-08, with the labels that each got.

#275 Add integration tests to gen3-helm repo
  gen3-integration-tests/gen3_ci/scripts/prepare_ci_environment.py
Labels: TestHomePage

#278 Add gen3sdk label
  gen3-integration-tests/pyproject.toml
  gen3-integration-tests/tests/test_data_upload.py
  gen3-integration-tests/tests/test_graph_submit_and_query.py
  gen3-integration-tests/tests/test_presigned_url.py
Labels: TestDataUpload, TestLoginPage

#281 Avoid common service block updates for services not deployed
  gen3-integration-tests/scripts/helm/env_setup.sh
Labels: TestAggregateMDS

#283 Move portal block into separate portal.yaml file
  gen3-integration-tests/scripts/helm/env_setup.sh
Labels: TestHomePage

#270 Update shared_integration_tests.yaml
  .github/workflows/shared_integration_tests.yaml
Labels: TestHomePage

#276 Nightly run on helm
  .github/workflows/nightly_run.yaml
  .github/workflows/shared_integration_tests.yaml
  gen3-integration-tests/docs/howto/run_tests/on_helm_local.md
  gen3-integration-tests/gen3_ci/scripts/generate_slack_report.py
  gen3-integration-tests/gen3_ci/scripts/teardown_helm_env.py
  gen3-integration-tests/pages/discovery.py
  gen3-integration-tests/pages/login.py
  gen3-integration-tests/services/ras.py
  gen3-integration-tests/tests/test_audit_service.py
  gen3-integration-tests/tests/test_ras_authn.py
  gen3-integration-tests/utils/test_setup.py
Labels: TestHomePage

#286 Fix nightly run
  .github/workflows/shared_integration_tests.yaml
Labels: TestHomePage

#288 Fix user-namespace issue for hatchery
  gen3-integration-tests/scripts/helm/env_setup.sh
Labels: TestDataUpload

#289 Delete indexd-userdb for nightly-build and update helm cleanup script
  gen3-integration-tests/gen3_ci/helm_cleanup/helm-ci-cleanup.yaml
  gen3-integration-tests/scripts/helm/env_setup.sh
Labels: TestHomePage

#293 Fix sequence of steps
  .github/workflows/shared_integration_tests.yaml
Labels: TestHomePage

#308 Allow 20 concurrent CI runs
  .github/workflows/shared_integration_tests.yaml
Labels: TestHomePage

#315 Terminate hanging workspace before launching a new one
  gen3-integration-tests/tests/test_workspace.py
Labels: TestWorkspacePage

#318 Add resouces to etl block on manifest setup
  gen3-integration-tests/gen3_ci/scripts/setup_ci_env.sh
Labels: TestETL
