Repository uc-cdis/gen3-code-vigil, pull requests merged in 2025-04, with the labels that each got.

#169 Ensure the PR is run under the same org as an Internal PR
  .github/workflows/shared_integration_tests.yaml
Labels: TestAuditService, TestAggregateMDS

#172 Update slack version
  .github/workflows/shared_integration_tests.yaml
Labels: TestHomePage

#171 Update dependencies
  .pre-commit-config.yaml
  gen3-integration-tests/poetry.lock
  gen3-integration-tests/pyproject.toml
Labels: TestHomePage

#174 Add Channel to slack payload
  .github/workflows/shared_integration_tests.yaml
  gen3-integration-tests/gen3_ci/scripts/generate_slack_report.py
Labels: TestHomePage

#175 Update test_workspace.py - Hatchery Skip
  gen3-integration-tests/pyproject.toml
  gen3-integration-tests/tests/test_workspace.py
Labels: TestHomePage

#170 Helm Env Setup
  gen3-integration-tests/gen3_ci/helm_scripts/helm_env_setup.sh
  gen3-integration-tests/gen3_ci/scripts/prepare_ci_environment.py
  gen3-integration-tests/utils/__init__.py
Labels: WIP

#176 "setup-fence-test-clients job" improvements
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-setup-fence-test-clients.groovy
  gen3-integration-tests/gen3_ci/scripts/release_ci_environment.py
  gen3-integration-tests/utils/gen3_admin_tasks.py
  gen3-integration-tests/utils/jenkins.py
Labels: TestHomePage

#177 DICOM tests: Take screenshot earlier
  gen3-integration-tests/pages/dicom.py
Labels: TestDicomViewer

#178 Add login for test report
  .github/workflows/shared_integration_tests.yaml
Labels: TestHomePage

#180 update button locator for submission test
  gen3-integration-tests/pages/submission.py
Labels: TestDataUpload

#183 Handle nightly builds
  .github/workflows/shared_integration_tests.yaml
  gen3-integration-tests/gen3_ci/scripts/generate_slack_report.py
Labels: TestHomePage

#187 Fix slack reporting of nightly builds
  gen3-integration-tests/gen3_ci/scripts/generate_slack_report.py
Labels: TestHomePage

#186 Increase memory size ci-only-setup-fence-test-clients.groovy
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-setup-fence-test-clients.groovy
Labels: TestHomePage

#189 Run integration tests only on changes to gen3-integration-tests folder
  .github/workflows/integration_tests.yaml
Labels: TestHomePage

#190 Increase resource limits for pods that modify envs for manifest PRs
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-modify-env-for-manifest-pr.groovy
Labels: TestHomePage

#191 Skip tests for release notes PRs
  .github/workflows/shared_integration_tests.yaml
Labels: TestHomePage

#192 Fix accidental comment from workflow
  .github/workflows/shared_integration_tests.yaml
Labels: TestHomePage
