Repository uc-cdis/gen3-code-vigil, pull requests merged in 2025-06, with the labels that each got.

#214 Add sower marker to required tests
  gen3-integration-tests/tests/test_discoverypage.py
  gen3-integration-tests/tests/test_pfb_export.py
Labels: TestHomePage

#207 Skip portal tests based on Portal Version
  .secrets.baseline
  gen3-integration-tests/conftest.py
  gen3-integration-tests/utils/gen3_admin_tasks.py
Labels: TestHomePage

#223 Update test_audit_service.py
  gen3-integration-tests/pages/login.py
  gen3-integration-tests/tests/test_audit_service.py
Labels: TestAggregateMDS

#224 Add nightly-run label when replaying nightly-build PRs
  .github/workflows/image_build.yaml
  gen3-integration-tests/gen3_ci/scripts/generate_slack_report.py
Labels: TestHomePage

#225 Fix Register User tests
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-check-register-users-on.groovy
  gen3-integration-tests/pages/exploration.py
  gen3-integration-tests/pages/login.py
  gen3-integration-tests/tests/test_register_user.py
  gen3-integration-tests/utils/gen3_admin_tasks.py
Labels: TestAuditService, TestRegisterUser

#227 Change user for Data Upload Portal Test
  gen3-integration-tests/tests/test_data_upload.py
Labels: TestAggregateMDS, TestGoogleDataAccess

#228 Handle Multiple buttons on Midrc Exploration page
  gen3-integration-tests/gen3_ci/jenkins_jobs/ci-only-check-register-users-on.groovy
  gen3-integration-tests/pages/exploration.py
Labels: TestRegisterUser
